In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('C:\\Users\\Hp\\Desktop\\automobile\\Automobile.csv')

In [3]:
df

,Name of the image,Color of the car,Manufacturer of the car,Type of car
0,download,White,Audi,Sports car
1,download (1),White,Audi,Sports car
2,download (2),White,Audi,Sports car
3,download (3),White,Audi,Sports car
4,4,Black,Acura,midsize upscale car
5,3,Black,Acura,midsize upscale car
6,1,Black,Acura,midsize upscale car
7,87,Red,Chrysler Group LLC,Mid-size pickup truck
8,54,Red,Chrysler Group LLC,Mid-size pickup truck
9,546,Red,Hyundai,hybrid and electric car
10,654,Red,Hyundai,hybrid and electric car
11,5464,Red,Hyundai,hybrid and electric car
12,5454,Black,Ford,Comercial Vehicle
13,8756,White,Ford,Comercial Vehicle
14,435213,White,Ford,Comercial Vehicle
15,123,Red,Chevrolet,convertible
16,12354,Red,Chevrolet,convertible
17,dd1,Black,FCA's Dodge,mid-size crossover SUV
18,dd2,Black,FCA's Dodge,mid-size crossover SUV
19,dc2,Red,Dodge,Performance car
20,dc5,Red,Dodge,Performance car
21,bv1,White,general motors,Compact car
22,bv2,White,general motors,Compact car
23,bv3,White,general motors,Compact car

In [4]:
import warnings
warnings.filterwarnings('ignore')
import os
import cv2

In [5]:
!pip install opencv-contrib-python-headless

Requirement already satisfied: opencv-contrib-python-headless in c:\users\hp\anaconda3\lib\site-packages (4.5.3.56)
Requirement already satisfied: numpy>=1.17.3 in c:\users\hp\appdata\roaming\python\python38\site-packages (from opencv-contrib-python-headless) (1.19.5)

In [6]:
auto_path= 'C:\\Users\\Hp\\Desktop\\automobile'

In [7]:
auto_path_audi= auto_path+'\\Audi TT'
auto_path_acura=auto_path+'\\Acura TL'
auto_path_buick= auto_path+'\\buick verano'
auto_path_dodged=auto_path+'\\Dodge Dakota'
auto_path_dodgej=auto_path+'\\dodge journey'
auto_path_ford= auto_path+'\\Ford Super duty'
auto_path_geo= auto_path+'\\Geo metro'
auto_path_hyundai= auto_path+'\\Hyundai Sonata Hybrid'